pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // Flutter's generated module and its Android plugins use project repositories.
    // Prefer this centralized set while allowing those generated projects to build.
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven("https://storage.googleapis.com/download.flutter.io")
    }
}

rootProject.name = "AetherEngine"

include(":android-host")
include(":fixture-guest")

// Generated by `flutter pub get` in flutter-app; do not check .android/ into Git.
// Aether's host embeds the Flutter module, so the generated subproject is required.
val flutterModuleInclude = File(settingsDir, "flutter-app/.android/include_flutter.groovy")
if (!flutterModuleInclude.isFile) {
    throw GradleException(
        "Flutter module is not bootstrapped. Run `cd flutter-app && flutter pub get` before invoking Gradle."
    )
}
apply(from = flutterModuleInclude)
