pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // Flutter's generated module and its Android plugins use project repositories.
    // Prefer this centralized set while allowing those generated projects to build.
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven("https://storage.googleapis.com/download.flutter.io")
    }
}

rootProject.name = "AetherEngine"

include(":android-host")

// Generated by `flutter pub get` in flutter-app; do not check .android/ into Git.
// This is Flutter's supported source-subproject add-to-app integration.
// Conditional include: when the Flutter module has not been bootstrapped
// (e.g. a host-only build on a machine without the Flutter SDK), :android-host
// still builds because it has no compile-time dependency on the Flutter embedding.
val flutterModuleInclude = File(settingsDir, "flutter-app/.android/include_flutter.groovy")
if (flutterModuleInclude.isFile) {
    apply(from = flutterModuleInclude)
} else {
    logger.lifecycle("settings: flutter-app/.android missing — skipping Flutter module include (host-only build)")
}
