pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // Flutter's generated module and its Android plugins use project repositories.
    // Prefer this centralized set while allowing those generated projects to build.
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven("https://storage.googleapis.com/download.flutter.io")
    }
}

rootProject.name = "AetherEngine"

include(":android-host")

// Generated by `flutter pub get` in flutter-app; do not check .android/ into Git.
// This is Flutter's supported source-subproject add-to-app integration.
val flutterModuleInclude = File(settingsDir, "flutter-app/.android/include_flutter.groovy")
require(flutterModuleInclude.isFile) {
    "Flutter module bootstrap is missing. Run `flutter pub get` in flutter-app first."
}
apply(from = flutterModuleInclude)
